exclude: 'build|third-party|.github'

default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
    # -   id: no-commit-to-branch
    #     args: ['--branch=main']
    -   id: end-of-file-fixer

-   repo: https://github.com/psf/black
    rev: 22.10.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+

-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
