# Config options for phase 1: training multi-subject head only
encoder: grouplin
trunk: eva02_base_patch14_224.mim_in22k
layers:
  - blocks.[02468]
  - blocks.10
embed_state: weights/group_pca_d-2048.pt
proj_dim: 2048
hidden_dim: 1024
epochs: 40
batch_size: 512
lr: 6.0e-4
weight_decay: 0.8
dropout: 0.9
crop_scale: 0.8
min_lr_fraction: 0.05
amp: true
